#!/bin/bash

echo "2"
i=0
while [ $i -le 10 ]
do
    /usr/bin/time -f "%e" ./h 2 < input-4.txt > /dev/null
    i=`expr $i + 1`
done
echo "64"
i=0
while [ $i -le 10 ]
do
    /usr/bin/time -f "%e" ./h 64 < input-4.txt > /dev/null
    i=`expr $i + 1`
done
