#!/bin/bash

echo "2"
i=0
while [ $i -le 10 ]
do
    time ./heap 2 < input-4.txt > /dev/null
    i=`expr $i + 1`
done
echo "64"
i=0
while [ $i -le 10 ]
do
    time ./heap 64 < input-4.txt > /dev/null
    i=`expr $i + 1`
done
