#!/bin/bash

i=2
while [ $i -le 100 ]
do
    echo "$i"
    j=0
    while [ $j -le 10 ]
    do
        /usr/bin/time -f "%U" ./heap "$i" < input-4.txt > /dev/null
        j=`expr "$j" + 1 `
    done
    i=`expr "$i" '*' 2  `
done
